name: Build Android (Release)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build Android Example App (release)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Setup JDK 17
        uses: actions/setup-java@v5.6.0
        with:
          distribution: "zulu"
          java-version: 17
          java-package: jdk

      - name: Restore Gradle cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Build for example/android/
        working-directory: example/android
        run: ./gradlew assembleRelease --no-daemon --build-cache

      - name: Upload APK to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            example/android/app/build/outputs/apk/release/app-release.apk#NitroSQLiteExample-${{ github.event.release.tag_name }}.apk \
            --clobber

      # Gradle cache doesn't like daemons
      - name: Stop Gradle Daemon
        working-directory: example/android
        run: ./gradlew --stop
